apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: fsx-provisioner
status: {}
spec:
  labels:
    fsx-node: 'true'
  providerRef:
    name: fsx-node-template
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - c5.large
        - c5.xlarge
        - c5.2xlarge
        - c5.4xlarge
        - c5.9xlarge
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - spot
        - on-demand
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
        - arm64
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
  ttlSecondsAfterEmpty: 120
  weight: 50
